### ISSUE TITLE
bot identificou equivocadamente que o cidadão queria RRL

### ISSUE THREAD

**Issue by AndreMalheiroPCRJ** [prefeitura-rio/chatbot-webhooks#140]
![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/142441059/a37eca4b-f2eb-4928-bff4-3d4135af612e)

no fluxo de PAL, o bot identificou equivocadamente que o cidadão queria RRL. numa primeira olhada, não identifiquei no texto algo que pudesse sugerir isso.

**Comment by BrunodePauloAlmeida** [comment]
O bot não finalizava a conversa quando o cidadão clicava em "voltar", fazendo com que a sessão continuasse erroneamente. Resolvido.
