### ISSUE TITLE
Atualizar Menus da Dívida Ativa

### ISSUE THREAD

**Issue by BrunodePauloAlmeida** [prefeitura-rio/chatbot-webhooks#175]
Foi alinhado que todos os menus do tipo abaixo devem aceitar tanto números (1,2) quanto as opções por escrito ("opção a", "opção b"). Isso vai valer para todos os fluxos, seja do 1746, Dívida Ativa e os próximos que vierem.

> Escolha uma Opção:
> 
> 1 - opção a
> 2 - opção b

Como os menus dos fluxos da Dívida Ativa atualmente aceitam apenas a opção numérica, vou precisar que vocês façam essa atualização neles, por favor. As páginas que vão precisar ter seus menus atualizados são:

- 1.1. Coletar opções para consulta de débito em DA
- 1.6 Se total não parcelados > 0 e total parcelados > 0
- 1.6 Se total não parcelados > 0 e total parcelados = 0
- 1.6 Se total não parcelados = 0 e total parcelados > 0
- DA - 3 : Coleta Opção de Consulta

Existe um vídeo tutorial no drive explicando como fazer essa atualização, passo a passo: https://drive.google.com/file/d/19-PO3TXSbi2CyxdBjr3IccfUx20EWj5U/view?usp=drive_link

**Comment by gutovysk** [comment]
Iniciando mudanças

**Comment by Arnaldorj** [comment]
Fluxo DA-3  : Coleta Opção de Consulta, concluída e testada.
1.6 Se total não parcelados > 0 e total parcelados > 0,1.6 Se total não parcelados > 0 e total parcelados = 0,1.6 Se total não parcelados = 0 e total parcelados > 0 concluídas, faltando testar.
