### ISSUE TITLE
Adicionar Route Groups

### ISSUE THREAD

**Issue by BrunodePauloAlmeida** [prefeitura-rio/chatbot-webhooks#179]
Adicionar Rout Groups: Saídas Padrões, em todas as páginas de todos os fluxos da Dívida Ativa.

Habilitar essas rotas permite com que o usuário possa voltar ao menu principal da ASCSAC ou encerrar o atendimento a qualquer momento, digitando "voltar" e "sair", respectivamente. Isso tem que ser uma feature padrão em todas as páginas de todos os fluxos que vamos desenvolver. Como as páginas da Dívida Ativa ainda não possuem isso, é necessário implementar.

Existe um tutorial de como fazer isso no drive: https://drive.google.com/file/d/1J2fWbanEF6Q7XMl5ybTEkBHH8md0wMDl/view?usp=drive_link

**Comment by gutovysk** [comment]
já realizada.
