### ISSUE TITLE
omitir CEP da confirmação do endereço

### ISSUE THREAD

**Issue by AndreMalheiroPCRJ** [prefeitura-rio/chatbot-webhooks#181]
há discrepâncias entre a informação de CEP que o google retorna e o da consulta de CEP, que é a referência. o resultado é que o usuário está dando resposta negativa na confirmação do endereço e fica repetindo o fluxo de endereço, ou então desiste.

como o CEP não é informação relevante ou requerida para a solicitação do serviço, sugiro omitir. @cynthiabimbi veja por favor se isso fere algo importante.

**Comment by BrunodePauloAlmeida** [comment]
Como a @cynthiabimbi não respondeu, eu já tirei. Vou subir essas modificações no fim do dia 28/11

**Comment by cynthiabimbi** [comment]
De acordo
