### ISSUE TITLE
Problema para abrir chamado

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#187]
Após a inclusão do último item, escrevi avançar e não foi aberto chamado. Apareceu uma mensagem de encaminhando a solicitação para um atendente. O chamado não foi aberto.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/17d4ef54-0dd4-432d-8342-22230ab3e78f)

**Comment by cynthiabimbi** [comment]
Validado após correção.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/dbbb364b-6104-4924-b547-dc3424bccb39)
