### ISSUE TITLE
Encerra o chamado sem concluir

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#188]
Testei propositalmente meu CPF cadastrado e ele reconheceu que o email fornecido estava errado. Apesar disso, após eu ter colocado o primeiro item para remoção (cama de casal), o sistema simplesmente tentou encaminhar o chamado para um atendente e, como não foi possível, encerrou o atendimento sem concluir.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/ee17a556-cf97-443c-a016-3f1094587003)

**Comment by BrunodePauloAlmeida** [comment]
@cynthiabimbi dá uma olhada nesse pfv

**Comment by cynthiabimbi** [comment]
parece sim ser problema de não informar a qtd... olhe caso abaixo. Mas acho ruim adotar qtd=1. Acho que tem q perguntar p usuário qual qtd do item solicitado


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/799a4a1c-625f-4ddb-a23e-07482f3ed48e)

**Comment by BrunodePauloAlmeida** [comment]
Quando a quantidade não é informada, adicionei a mensagem abaixo:


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/a429ace2-6bde-4b85-8da2-a8681e01286c)


Alteração sobe no fim do dia 28/11.

**Comment by cynthiabimbi** [comment]
Validado o ajuste , porém texto está repetitivo. Favor deletar marcado em amarelo



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/72ed0636-f5da-471c-97b0-0ee0c01ced72)

**Comment by BrunodePauloAlmeida** [comment]
Texto ajustado. Modificação sobe no fim do dia 29/11.

**Comment by cynthiabimbi** [comment]
Correção validada
