### ISSUE TITLE
Problema para incluir mais um item no chamado

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#189]
Já tinha solicitado a remoção de entulho e tentei incluir armário e apareceu a mensagem de encaminhado a solicitação para um atendente. No site do 1746, não permite solicitar a remoção de entulho e a retirada de armário.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/c8b31aea-f2a9-40b7-b454-77c70764624a)

**Comment by BrunodePauloAlmeida** [comment]
Quando a quantidade não é informada, o bot estava tendo problemas, então adicionei a mensagem abaixo:


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/a429ace2-6bde-4b85-8da2-a8681e01286c)


Alteração sobe no fim do dia 28/11.

**Comment by cynthiabimbi** [comment]
Validado ajuste aplicado. Fica pendente apenas nova correção solicitada no #188
