### ISSUE TITLE
Problema ao incluir item e não informar quantidade

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#190]
Tentei solicitar a retirada de maquina de lavar e não informei a quantidade, fui encaminhada para um atendente.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/69e76a14-9fee-47c7-93e2-682eee9fccb0)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/d0e69017-d6e3-4b92-9c3d-56277d6ac7d6)

**Comment by BrunodePauloAlmeida** [comment]
Quando a quantidade não é informada, o bot estava tendo problemas, então adicionei a mensagem abaixo:


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/a429ace2-6bde-4b85-8da2-a8681e01286c)


Alteração sobe no fim do dia 28/11.

**Comment by cynthiabimbi** [comment]
Validado ajuste aplicado. Fica pendente apenas nova correção solicitada no #188
