### ISSUE TITLE
Erro na informação complementar

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#191]
Quando o sistema perguntou se existe alguma informação complementar, eu disse que SIM, mas ele não reconheceu a resposta de imediato e seguiu com outras perguntas. Só no final do atendimento que voltou a fazer a mesma pergunta sobre informação complementar.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/dc06d9cf-04b7-4bff-8eba-17b2a902460b)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/d5ba0e24-d620-4f65-a2ba-235df43f0566)

**Comment by BrunodePauloAlmeida** [comment]
Incluir um intent em que se o cidadão informa "sim", perguntamos novamente a informação complementar, em vez de seguir.

**Comment by BrunodePauloAlmeida** [comment]
Adicionado, alteração sobe no fim do dia 28/11.


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/e1f18785-a20d-4064-9867-6869707831b9)

**Comment by cynthiabimbi** [comment]
Respondi direto qual era a info complementar, ao invés de dizer sim. Info complementar gravada com sucesso
RIO-27644315-8 

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/65e08e0b-f04d-41ce-87a2-ce0ddd344432)
