### ISSUE TITLE
Dificuldade em reconhecer o endereço

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#195]
Quando testei colocar a rua separado da numeração, o sistema reconheceu apenas o nome da rua. Ele só conhece os dois caso estejam juntos.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/1e9443a1-4e70-459c-b040-947b9bfd8b53)

**Comment by BrunodePauloAlmeida** [comment]
Isso é esperado. O bot reage após a primeira mensagem enviada pelo usuário, em cada passo. Não tem muito o que fazer, é o funcionamento padrão da maioria dos chatbots.

**Comment by liviavairo** [comment]
Entendido
