### ISSUE TITLE
Erro no endereço

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#196]
Tentei colocar o endereço somente com rua e número, mas o sistema errou o bairro. Tentei incluir o bairro na segunda vez, mas ele continuou errando. Somente na terceira tentativa ele acertou.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/fed2b68a-f08f-4e2f-b6d1-98ade0c75ff3)

**Comment by BrunodePauloAlmeida** [comment]
Na segunda tentativa, o usuário preencheu um novo endereço em vez de responder se o endereço estava correto ou não. É necessário primeiro responder "sim" ou "não", antes de informar um novo endereço.


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/9b8318e5-0b0d-4f72-b3cb-a5825571bd72)


No fim, o usuário conseguiu responder corretamente a pergunta e informar o novo endereço, que foi identificado corretamente. Eu interpreto como sucesso.
