### ISSUE TITLE
Erro de complemento

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#197]
Tentei colocar a necessidade de agendamento como complemento, mas o sistema não reconheceu e encerrou a sessão.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/36e6007c-2175-492c-b90c-400c3a6aa301)

**Comment by BrunodePauloAlmeida** [comment]
Essa informação de "precisa agendar" deveria ser informada na Coleta de Informações Complementares, ao meu ver.

Mas, mesmo assim, o sistema capturou essa frase de precisar agendar e colocou no campo de complemento do chamado, como dá pra ver abaixo.

`

> Address(localidade=, codigoLogradouro=063933, logradouro=Avenida Dom Hélder Câmara, numero=89, codigoBairro=12, bairro=Benfica, complemento=precisa agendar, cep=20911-291, coordenadaX=, coordenadaY=, urlFoto=, tipoEndereco=Condomínio)

`

O funcionamento está como esperado.

**Comment by liviavairo** [comment]
Entendido
