### ISSUE TITLE
Problema para aceitar nome

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#198]
Não aceitou a identificação com o nome de Shakira da Silva.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/cef61ad7-5f1d-4535-b9d3-90887f49bc48)

**Comment by BrunodePauloAlmeida** [comment]
Por algum motivo o bot estava entendendo que "Shakira da Silva" era equivalente a "de jeito nenhum" ou "de maneira alguma", sinônimos de "não". Logo, identificando que o cidadão não queria informar o nome, que é obrigatório.

Problema resolvido. "Shakiras da Silva" podem agora abrir chamados!
