### ISSUE TITLE
Problema para confirmar item solicitado

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#200]
Em um único chamado, solicitei a retirada de 2 armários de cozinha e foi ok. Ai inclui 2 aspiradores de pó. Na mensagem de confirmação do objeto não aparece o nome do objeto informado, o nome fica em branco. Mesmo assim confirmei o objeto e fui incluir outro. Na mensagem que informa os objetos que foram solicitados a remoção, não contabiliza o segundo objeto confirmado, aparece somente os armários. Os aspiradores de pó só aparecem após incluir uma cama e aparece somente 1, e pedi para remover 2. Mesmo com essa divergência consegui abrir o chamado. RIO-27644258-5.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/85b6b09b-38d0-4631-b740-6bd28ee54bfd)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/34bb7ca4-c297-4cde-920b-03d96f03ba7b)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/1b049bb3-73d1-4e2c-97f9-ee2c194b64c6)

**Comment by BrunodePauloAlmeida** [comment]
Esse erro aconteceu por 2 motivos:

1. Quando o usuário não confirmava um item ou dizia que queria adicionar um novo item, os valores já capturados de nome e quantidade de item não estavam sendo reiniciados para a nova coleta. Isso estava causando com que as quantidades dos itens estivessem sido trocadas. **Já foi corrigido, sobe no fim do dia 28/11**

2. O usuário estava enviando mensagem antes do bot enviar todas as mensagens, como no caso abaixo. Eu pretendo resolver isso colocando todas as informações em uma única mensagem. Mas isso será feito amanhã, dia 29/11.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/d061bfc4-a65c-4f7e-ade3-1dbaf4858980)

**Comment by BrunodePauloAlmeida** [comment]
Bot agora está enviando as mensagens todas juntas. Modificação sobe agora.

**Comment by cynthiabimbi** [comment]
Correção validada



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/42a9a3d5-85fa-42a6-8c07-0c295191f052)
