### ISSUE TITLE
Problema para solicitar retirada de sacos de gesso

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#201]
Solicitei a retirada de 10 sacos de gesso e apareceu a mensagem de encaminhando para um atendente.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/5f2ac0fe-cf02-404d-9758-b4f80001270d)

**Comment by BrunodePauloAlmeida** [comment]
O transbordo aconteceu porque o bot capturou que a unidade é 10, mas não conseguiu conectar "gesso" com nenhum dos materiais cadastrados. 

Impedi com que o bot siga de etapa caso capture só a quantidade e também coloquei que "gesso" equivale a "entulho".

A modificação sai no fim do dia 28/11.

**Comment by cynthiabimbi** [comment]
No caso do gesso, tem que ser interpretado este objeto corretamente,  e não colocar igual entulho. As limitações de volume são bem diferentes.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/8b434f98-e53a-4909-be59-2565feedb51a)

**Comment by BrunodePauloAlmeida** [comment]
Aparentemente eu deixei esse item de gesso passar. Adicionei ele a lista de itens permitidos. Alteração sobe no fim do dia 29/11.


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/cf921e57-a1d3-4e46-acc1-5c7b0f0fa610)

**Comment by cynthiabimbi** [comment]
Correção validada


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/a2b28874-92c2-45b6-b512-8503fbd8981c)
