### ISSUE TITLE
Problema para solicitar retirada de 6 bancos

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#202]
Solicitei a retirada de 6 bancos e aparece a mensagem que o limite para remoção de pias/bancadas/cubas é de 3 unidades, mas banco esta com cadeiras no site do 1746 e pode solicitar a retirada de 6 unidades.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/d5f3a6c8-9f52-4ee4-8a17-3347ef7c8c44)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/a9dd0506-3027-468f-a9c5-3d66ab00eaa0)

**Comment by BrunodePauloAlmeida** [comment]
Banco provavelmente está ligado com "bancada" e não "cadeira"

**Comment by brunalopes2024** [comment]
Mas no site do 1746 tem a opção de cadeiras/bancos, podendo escolher 6 unidades.

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/bef7a434-9a49-4b38-abfe-31d7644c9e86)

**Comment by BrunodePauloAlmeida** [comment]
Certo. Vou corrigir para que o bot identifique corretamente que banco é cadeira

**Comment by brunalopes2024** [comment]
Cadeira também está com erro e enviando para o atendente.
![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/64f4ead5-29b6-43b1-a616-00c89be308cd)

**Comment by BrunodePauloAlmeida** [comment]
Corrigido. Agora "banco" equivale a "cadeira", em vez de "bancada". 

A alteração sobe no fim do dia 28/11.
