### ISSUE TITLE
Desistência de incluir item

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#204]
Adicionei os sacos de entulho e disse que queria adicionar mais itens. Logo depois, agi como se tivesse desistido e tentei escrever "AVANÇAR", mas o sistema entende como erro e tenta fazer o encaminhamento para atendente. Não gerou protocolo.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/c40092d6-3151-45d7-b1b1-c36c818ca3ec)

**Comment by BrunodePauloAlmeida** [comment]
O problema era a rota "avançar" que estava desconfigurada. Problema foi resolvido ontem 28/11.

**Comment by cynthiabimbi** [comment]
Cenário de 'avançar' não cair no atendente Validado em outra issue
