### ISSUE TITLE
Problema para solicitar retirada de tacos

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#205]
Ao tentar solicitar retirada de tacos, apareceu a mensagem de encaminhando solicitação para atendente.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/e015436f-747d-49c7-a4ab-8d422150eda7)

**Comment by BrunodePauloAlmeida** [comment]
Problema estava relacionado a não informar a quantidade do item. Problema foi resolvido ontem 28/11.

**Comment by cynthiabimbi** [comment]
Correção validada



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/3e207b43-96f8-4d69-8f08-6fe0cbea4e46)
