### ISSUE TITLE
Problema para solicitar retirada de tacos

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#206]
Ao solicitar a retirada de 10 sacos de 20 litros de taco o sistema entende latão de 200 litros e ao solicitar 1 saco de 20 litros de tacos , o sistema entende 1 unidade de latão de 200 litros. Só entende que é taco, quando escrevo Tacos - 1 saco de 20 litros.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/425c427c-5e0f-4d6e-b248-d59b768c4e8c)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/ff010ba9-6779-48ca-9855-ef83bd45f7c7)

**Comment by BrunodePauloAlmeida** [comment]
Problema de reconhecimento de tacos aparentemente já foi resolvido. Testei agora, 29/11 às 13h30 e ele reconheceu normalmente.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/1b3bed79-b240-44f1-a4ca-a222840d8379)

**Comment by cynthiabimbi** [comment]
Correção validada



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/2e183501-698d-4da4-a1e8-d9fd6e304f7c)
