### ISSUE TITLE
Problema para avançar

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#207]
Solicitei a retirada de 3 objetos e informei sim para incluir mais um, mas desisti após aparecer a mensagem: Caso não queira adicionar mais nenhum item, responda AVANÇAR. Escrevi avançar e direcionou para um atendente.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/9d14e80d-b587-4aaf-bfa5-12c923d0b19b)

**Comment by BrunodePauloAlmeida** [comment]
O problema era a rota "avançar" que estava desconfigurada. Problema foi resolvido ontem 28/11.

**Comment by cynthiabimbi** [comment]
Já validado em outra issue
