### ISSUE TITLE
Comando p armario não compreendido

### ISSUE THREAD

**Issue by cynthiabimbi** [prefeitura-rio/chatbot-webhooks#208]
Solicitei recolher '2 armario cozinha'  e robo não entendeu. Só entende quando coloco nome exato do produto

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/b75e99da-8fcc-4e29-b819-f9cf6bc94d15)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/89d04c26-805b-472d-b74c-887c80934d7b)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/1db9940a-b5c9-4cf6-8dd0-7eb963d65cb2)

**Comment by BrunodePauloAlmeida** [comment]
Problema de identificação de "armário de cozinha" aparentemente resolvido. Testei agora, 29/11 às 13h40 e ele identificou corretamente.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/afdc122c-066c-4f42-8bcb-2cfc752912ef)
