### ISSUE TITLE
Problema para solicitar retirada de 5 janelas

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#209]
Ao solicitar a retirada de 5 janelas, o sistema informa que é permitido a retirada de somente 4 janelas, mas no site do 1746 permite 5.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/2c5a5f04-edbb-4c9e-93d3-db353afee148)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/fcc3329d-2266-41f1-8697-1398842b8c76)

**Comment by BrunodePauloAlmeida** [comment]
@cynthiabimbi pode me ajudar aqui? Na tabela que você me passou na planilha `Subtpos com atributos`, existem 2 itens que contém "janela" na descrição.

Linha 13: 

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>
12 | CAIXONETE DE PORTA/JANELA | 5 | amarrados de até 1,5 m | VERDADEIRO | VERDADEIRO | 1
-- | -- | -- | -- | -- | -- | --



</body>
</html>

**Comment by cynthiabimbi** [comment]
Concordo ligar com 45

**Comment by BrunodePauloAlmeida** [comment]
Certo. Nesse caso, já está ligado corretamente.

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/d1fb56a4-c4b3-4170-8536-44b876bbf69b)

**Comment by cynthiabimbi** [comment]
Correção validada



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/e7689adc-8217-473d-a1b7-66a5c10905df)
