### ISSUE TITLE
Problema ao informar complemento

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#213]
Na pergunta: Tem complemento? Se sim, diga. Respondi que sim e não coloquei o complemento, o sistema não deveria perguntar qual o complemento?

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/129b1169-5294-42a3-90ec-8707466f81e7)

**Comment by BrunodePauloAlmeida** [comment]
O esperado é que a pessoa vá dizer direto o complemento, e não "sim" para depois dizer o complemento. Mas vou colocar essa opção, já que entendo que o usuário pode interpretar assim.

**Comment by BrunodePauloAlmeida** [comment]
Mudança feita. Sobe no fim do dia 29/11.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/3592b116-9858-4f37-8b28-61f28f1bf492)
