### ISSUE TITLE
Msg info complementar com erro

### ISSUE THREAD

**Issue by cynthiabimbi** [prefeitura-rio/chatbot-webhooks#214]
Msg info complementar sendo repetida varias vezes, não deixando fluxo seguir.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/387c6778-f452-480f-8ac2-de6b2d345240)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/9e8d3eb7-13a6-4b78-813e-e045dd118513)

**Comment by BrunodePauloAlmeida** [comment]
Ele estava interpretando "quero" como "sim". Mas já foi corrigido. Mudança sobe no fim do dia 29/11
