### ISSUE TITLE
E-mail incompleto

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#221]
Ao conferir o chamado, verifiquei que não aparece o br no final do e-mail.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/453e3f4e-b3c8-4d6e-9424-22bf58381d8b)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/5825b333-3220-4c6c-a758-ec8be8595122)

**Comment by BrunodePauloAlmeida** [comment]
Você teria o protocolo desse chamado?

**Comment by BrunodePauloAlmeida** [comment]
Eu achei o protocolo e conferi exatamente o que aconteceu nessa conversa. Me parece um caso bem parecido com o #216 , já que enviamos o campo corretamente para o SGRC mas o cadastro foi feito errado. 

Making POST request to http://api-pcrj-hml.datametrica.com.br/PCRJ_180/PCRJ_WS_PortalWeb_Rest/api/WSPortalWeb/NovoChamado with data {'codigoClassificacao': '1607', 'dataHora': '2023-11-28T17:28:34', 'descricao': 'MATERIAIS A REMOVER: forno de microondas/elétrico - 1, aquecedor/cx descarga - 1, armário peq até 3 portas/cômoda - 1, grade de madeira ou ferro - 4, estante/rack - 1.', 'solicitantePortalWeb': **{'nome': 'Rodnei da Silva Alves', 'email': 'rodneialves_1978@lover.com.br', 'codigoIdioma': '', 'codigoPaisDDI': '', 'cpf': '10302717048'**, 'identidade': '', 'sexo': '', 'dataNascimento': '', 'endereco': {'localidade': '', 'codigoLogradouro': '', 'logradouro': '', 'numero': '', 'codigoBairro': '', 'bairro': '', 'complemento': '', 'cep': '', 'coordenadaX': '', 'coordenadaY': '', 'urlFoto': '', 'tipoEndereco': ''}, 'telefones': {'telefoneR': '', 'telefone1': '', 'telefone2': ''}}, 'codigoOrigemOcorrencia': '28', 'endereco': {'localidade': 'casa 1 vai abrir o portão', 'codigoLogradouro': '061523', 'logradouro': 'Avenida Marechal Floriano', 'numero': '117', 'codigoBairro': '5', 'bairro': 'Centro', 'complemento': 'casa 17', 'cep': '20071-002', 'coordenadaX': '', 'coordenadaY': '', 'urlFoto': '', 'tipoEndereco': 'Vila'}, 'atributosEspecificos': [], 'token': 't0d0!ws_p0rt@lweb'} and headers {'Content-Type': 'application/json', 'Accept': 'application/json', 'Authorization': 'UENSSkAyMDIzOlBzbFdVN1l2'}

Será que o erro está só no PDF da extração ou realmente está cadastrado errado no SGRC homologação?

**Comment by cynthiabimbi** [comment]
Realmente o erro foi na geração do pdf, pois consultando direto portal está tudo certo...
![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/40503571-d2b8-4817-ad1d-2a2d17f427ab)
