### ISSUE TITLE
Teste de item sem especificações

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#222]
Pedi a remoção de uma "cama", sem fornecer quantidade, nem tipo. O sistema respondeu alertando para a importância dessas especificações. Logo em seguida, coloquei "1 cama" e ele compreendeu que se tratava de uma cama de solteiro, disse que não era possível acrescentar aos itens a serem removidos e não me ofereceu a opção de cama de casal. Somente quando eu digitei "1 cama de casal" é que pude acrescentar. 

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/c072739e-3e4e-48e0-a7b4-406987a00e3d)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/b692b190-31b6-43db-9c17-2fa3937eb637)

**Comment by BrunodePauloAlmeida** [comment]
Funcionalidade adicionada. Agora ao falar "cama", o bot não assume nada e em vez disso ele mostra as opções com cama. Alteração sobe no fim do dia de hoje 01/12.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/39a57d3a-943a-4430-8a30-e3c224d818b9)

**Comment by cynthiabimbi** [comment]
De acordo
