### ISSUE TITLE
Problema na informação complementar

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#223]
Inseri uma informação complementar informando que os vasos de planta não tem terra. Ao conferir o chamado não encontrei a informação após a descrição do material a ser removido.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/8886b4ff-9fed-4196-9341-b1e66e41099f)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/b3d2af88-2aee-49c6-9f1a-bd552c6bc50b)

**Comment by BrunodePauloAlmeida** [comment]
Problema resolvido. O identificador de intenções do passo "Informações Complementares" estava muito sensível. Então a frase "os vasos de planta não tem terra" foi identificada como "não", por isso não foi a informação complementar. Mas isso já foi resolvido.
