### ISSUE TITLE
Quantidade separada do item

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#226]
Testei colocar o item (entulho) sem especificar a quantidade e, logo depois, a quantidade (3). Como era esperado, o sistema não reconheceu. Em seguida, testei o termo "3 sacos" e ele achou que se tratava de 3 sacolas de taco. Somente quando especifiquei que se tratavam de 3 sacos de entulho é que consegui computar.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/84869a62-9170-4bd2-88fe-2a3a3ee3a2c4)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/4dd21631-e67e-4c09-a104-3835a0f1a8a5)

**Comment by cynthiabimbi** [comment]
De acordo
