### ISSUE TITLE
Problema para solicitar 2 colchoes

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#227]
Tentei solicitar a remoção de 2 colchoes e o sistema não entende.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/39047965-600d-487c-8af6-6c36e0f3dad9)

**Comment by BrunodePauloAlmeida** [comment]
Resolvido. Sobe no fim do dia 30/11

**Comment by cynthiabimbi** [comment]
Correção validada.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/895a3436-fbe9-4680-89ba-5ed1aaeb7cd6)
