### ISSUE TITLE
Erro ao finalizar chamado

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#228]
Eu tinha aberto um chamado para a retirada de um fogareiro elétrico. O sistema acabou computando como forno elétrico e aceitou. Preenchi os itens de endereço, mas no momento do complemento, houve algum erro. Ele não aceitou finalizar o chamado.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/6f428c56-ebcb-449f-aa9e-48f100064026)

**Comment by BrunodePauloAlmeida** [comment]
O problema era o endereço "Rua Visconde de Itamaraty, 68". Problema resolvido no fim do dia 30/11.

**Comment by cynthiabimbi** [comment]
Por favor, informe o erro e a correção aplicada para eu poder fechar esta issue.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/69cf0fe2-d4bd-4c77-b4ad-187970088668)

**Comment by BrunodePauloAlmeida** [comment]
O erro era que para o endereço "Rua Visconde de Itamaraty, 68", o IPP não identificava o bairro. Então eu tentava abrir o chamado com o logradouro do IPP + bairro do Google, que no caso era "Rua Visconde de Itamaraty, 68, Tijuca". Só que na base do IPP, esse logradouro só estava ligado ao Maracanã e um outro bairro, não tinha Tijuca dentre as opções. Aí dava erro.

Agora eu faço 3 consultas em API's diferentes do IPP pra tentar achar um bairro válido. Nesse caso aí eu consigo achar. Mas nos casos em que não dá certo, o cidadão não segue, aparece a mensagem de endereço não encontrado.

**Comment by cynthiabimbi** [comment]
ok
