### ISSUE TITLE
Problema com a informação complementar

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#229]
Ao inserir a informação complementar: O latão tem 150 litros. O sistema não entende e continua perguntando qual a informação.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/337dfaaa-d542-4db4-bee8-9baa24402ccc)

**Comment by BrunodePauloAlmeida** [comment]
Resolvido. Sobe no fim do dia 30/11.

**Comment by cynthiabimbi** [comment]
Fluxo de informação complementar foi alterado, logo o report desta issue não faz mais sentido existir.
