### ISSUE TITLE
Erro após complemento

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#231]
Ao responder não para a pergunta de complemento. O sistema não concluiu a solicitação.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/1764153f-290f-4c77-9b3c-2c297800a524)

**Comment by BrunodePauloAlmeida** [comment]
Aqui o problema está no endereço. Especificamente na "Rua Vinte e Quatro de Maio, número 13".

Testei os endereços Rua Vinte e Quatro de Maio números 10,11,12,13,14 e 15. E só dá problema no 13. 

Como é algo muito específico e foge do contexto do fluxo de Remoção de Entulho, vou deixar para resolver depois.

**Comment by BrunodePauloAlmeida** [comment]
Problema corrigido. Sobe no fim do dia 30/11.

**Comment by cynthiabimbi** [comment]
Existe outra issue relatando problema com este endereço, logo estou fechando esta.
