### ISSUE TITLE
Erro com complemento

### ISSUE THREAD

**Issue by RobertaColosimo** [prefeitura-rio/chatbot-webhooks#232]
Tentativa de abertura de chamado para remoção de bens inservíveis - erro no final do fluxo de inserção de endereço. O robô pergunta se há complemento, a resposta é não e o chamado não é registrado 

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152509591/e1f162b6-e668-4843-8f8a-64076199c3e8)

**Comment by BrunodePauloAlmeida** [comment]
O problema desse chamado não foi o complemento, mas sim o nome informado pelo usuário: "Roberta 1".

O SGRC retornou o seguinte erro: **Sobrenome de pessoa inválido, pois possui menos de dois caracteres.**

Coloquei uma verificação adicional para que a pessoa seja obrigada a informar um sobrenome válido.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/f3e3e4f2-75b6-4298-af77-152e981f818d)

Sobe hoje, 30/11.

**Comment by cynthiabimbi** [comment]
Entendido
