### ISSUE TITLE
Abertura de chamado não permitido

### ISSUE THREAD

**Issue by cynthiabimbi** [prefeitura-rio/chatbot-webhooks#239]
Consegui abrir um novo chamado (em homologação) no meu cpf mesmo tendo chamado aberto (sem fechamento) em produção. Isso não deveria ser permitido pois não é permitido abrir chamado para mesmo cpf que tem outro chamado sem atendimento.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/c5a5884b-1a3b-47b4-a4c3-5b370c0d98a3)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/60250396-dcf0-4ad6-80c4-3f3578f35c20)

**Comment by BrunodePauloAlmeida** [comment]
Corrigido. Sobe no fim do dia de hoje 30/11.

**Comment by cynthiabimbi** [comment]
Correção validada p mesmo cpf, porém para mesmo endereço não foi corrigido.

CPF

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/da505a13-ba40-4f37-a7a2-912b68d1c69d)

Endereço


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/8913149c-84d3-4d17-8005-f3fa6db67a5b)

**Comment by BrunodePauloAlmeida** [comment]
Para mesmo endereço é outro issue. É o #236

**Comment by cynthiabimbi** [comment]
Correção validada p mesmo cpf.
