### ISSUE TITLE
Complemento não foi computado

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#242]
No chamado RIO-27644298-0, eu coloquei nos complementos que não se tratava de uma geladeira, mas sim de um frigobar. Ainda assim, o complemento não foi computado.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/22113cac-fb64-44fb-882c-255f839c2f8e)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/214ff7a8-9391-47b5-bdca-16fb430c6724)

**Comment by BrunodePauloAlmeida** [comment]
O comando para passar de passo era "não". Então frases com "não" estavam passando direto. Conversei com Malheiro e trocamos o texto para que o comando seja "avançar". Problema resolvido ontem 30/11.

OBS: caso a frase tenha a palavra "avançar", a informação complementar não será computada. Infelizmente não tem muito o que fazer, precisamos de um termo para usar.

**Comment by cynthiabimbi** [comment]
De acordo
