### ISSUE TITLE
Não reconheceu a palavra "azulejo"

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#244]
Fiz um chamado para a retirada de 1 pia, 1 vaso sanitário, 1 banheira e 10 caixas de azulejo. O sistema reconheceu todos, exceto o azulejo. Chamado RIO-27644358-2.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/969aa465-a5e8-460a-9d49-82a98b997e23)

**Comment by BrunodePauloAlmeida** [comment]
A pergunta para esse passo era "Deseja incluir outro material para ser retirado? (responda **SIM ou NÃO**)"

Então é esperado que o usuário responda sim ou não. Sim para incluir outro material, não para não incluir outro material.

Azulejo é reconhecido caso informado no passo correto.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/c94cbd8b-8c76-475f-b70f-dbfcc7b22bd0)

**Comment by cynthiabimbi** [comment]
Entendido
