### ISSUE TITLE
Computou pedido errado e encaminhou para atendente

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#245]
Pedi a retirada de 1 computador e 1 impressora. O sistema só registrou quando coloquei a quantidade total dos dois juntos. Mas quando fui pedir outro item (1 mesa), vi que ele tinha computado apenas 1 computador/impressora. Além disso, me encaminhou para o atendente sem motivo.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/25ae92a1-53fb-4fbb-9351-0d79897d0fda)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/aaef388b-9c53-40af-804a-178e803bb161)

**Comment by BrunodePauloAlmeida** [comment]
O problema aqui é que eu ainda estava aceitando informar mais de um item por vez... Então você informar 1 computador e 1 impressora e depois informar "2 computador e impressora" estava gerando alguns problemas.

Agora é realmente apenas 1 item por vez, não adianta tentar informar 2, ele só vai capturar 1 (não tenho como controlar qual, algum dos informados).

Já corrigi. Alteração sobe no fim do dia 01/12.

**Comment by cynthiabimbi** [comment]
ok
