### ISSUE TITLE
Não reconhece "colchão"

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#247]
Tentei colocar apenas "colchão" e "1 colchão" para ver se ele me dava opção de solteiro ou casal, mas ele não reconheceu nem quando eu especifiquei que se tratava de 1 colchão de casal. Segui o chamado sem o colchão. O protocolo é RIO-27644362-2.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/8ea334d9-c5de-4563-ab55-bfa2ac811fa8)

**Comment by BrunodePauloAlmeida** [comment]
A pergunta para esse passo era "Deseja incluir outro material para ser retirado? (responda **SIM ou NÃO**)"

Então é esperado que o usuário responda sim ou não. Sim para incluir outro material, não para não incluir outro material.

Colchão é reconhecido caso informado no passo correto.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/059d468d-13f7-4955-98c8-43087b0baf4a)

**Comment by cynthiabimbi** [comment]
De acordo
