### ISSUE TITLE
texto de limite de telhas precisa correção

### ISSUE THREAD

**Issue by RobertaColosimo** [prefeitura-rio/chatbot-webhooks#248]
o texto q mostra a quantidade limite de telhas a serem retiradas está com erro

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152509591/b73f06cd-3eae-42b4-859d-8c032a8934e1)

**Comment by BrunodePauloAlmeida** [comment]
Verdade. Texto corrigido.

**Comment by cynthiabimbi** [comment]
ok
