### ISSUE TITLE
Problema para avançar

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#249]
Após solicitar a informação do complemento, não tinha complemento, escrevi avançar. o Sistema encaminhou para um atendente. 

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/be834e58-04fb-4603-9a09-23a7ce9ed632)

**Comment by BrunodePauloAlmeida** [comment]
Foi algum bug atípico. Testei agora com exatamente as mesmas mensagens do usuário e funcionou normalmente. Peço que testem novamente, por favor. Abaixo está as mensagens enviadas pelo usuário em ordem.

**mensagem_cidadao**
928.372.660-00
sabrava_ss@lover.com.br
Senor Abravanel
2 conchoes
2 colchoes
2 colchoes de solteiro
sim
nao
avancar
1
av paris 192
sim
avancar

**Comment by cynthiabimbi** [comment]
Correção validada



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/d17c0976-22a1-4bbc-a37a-6c9bd33ebba6)
