### ISSUE TITLE
Problema com informação complementar

### ISSUE THREAD

**Issue by brunalopes2024** [prefeitura-rio/chatbot-webhooks#250]
Colocou uma informação complementar no momento da solicitação e não apareceu no pdf.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/856d9b40-a3c0-40bb-aec9-d933db84a072)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152203534/cbbae24a-45fb-4ed1-ad30-e29b2a602202)

**Comment by BrunodePauloAlmeida** [comment]
O comando para passar de passo era "não". Então frases com "não" estavam passando direto. Conversei com Malheiro e trocamos o texto para que o comando seja "avançar". Problema resolvido ontem 30/11.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/e0d79f0c-3fea-4a7b-a404-bcd6840a1c7f)



OBS: caso a frase tenha a palavra "avançar", a informação complementar não será computada. Infelizmente não tem muito o que fazer, precisamos de um termo para usar.

**Comment by cynthiabimbi** [comment]
ok
