### ISSUE TITLE
Não reconhece o termo "tapete"

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#253]
Tentei pedir a retirada de 1 porta, 2 aspiradores e 5 tapetes, mas o sistema não reconheceu os tapetes. Segui o chamado sem eles.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/7ae7abfc-9d23-4948-a8d3-ca0a4e433709)

**Comment by BrunodePauloAlmeida** [comment]
A pergunta para esse passo era "Deseja incluir outro material para ser retirado? (responda **SIM ou NÃO**)"

Então é esperado que o usuário responda sim ou não. Sim para incluir outro material, não para não incluir outro material.

Tapete é reconhecido caso informado no passo correto.


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/5e240f6b-9ca7-49ac-a70d-ff84cdf95ae3)

**Comment by cynthiabimbi** [comment]
Entendido
