### ISSUE TITLE
nao identifica o item 'outros'

### ISSUE THREAD

**Issue by RobertaColosimo** [prefeitura-rio/chatbot-webhooks#254]
Bot nao identifica o item 'outros'

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152509591/6e220a06-553e-41b1-b138-94ec53b8a729)

**Comment by BrunodePauloAlmeida** [comment]
E deveria @cynthiabimbi ? Eu propositalmente tirei ele da lista dos itens permitidos porque eu entendo que "Outros" é uma opção humana, para o atendente preencher. 

Não sei se deixar o cidadão poder informar "1 outros" é uma boa opção. O que você acha?
