### ISSUE TITLE
item nao reconhecido

### ISSUE THREAD

**Issue by RobertaColosimo** [prefeitura-rio/chatbot-webhooks#255]
a solicitação de 2 armarios de 3 portas não foi reconhecida

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152509591/4cf763e6-efde-4e03-b4e1-aa612c4f701c)

**Comment by cynthiabimbi** [comment]
Correção validada



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/8e639760-9136-42bc-be14-65a57abf4d97)
