### ISSUE TITLE
Encaminhou para o atendente e não finalizou o chamado

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#256]
![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/f596ea43-d006-4c8f-9e98-3ebdd59d7b6b)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/ab63a64e-ee19-4ea2-9330-774b810c8431)

**Comment by BrunodePauloAlmeida** [comment]
Foi um erro atípico. Testei agora exatamente com as entradas do usuário e funcionou. Peço que tentem de novo, por favor. Segue as mensagens enviadas pelo usuário, em ordem.

**mensagem_cidadao**
781.285.260-14
igorrosa@teste.com
Igor Rosa
52sacos de entulho
sim
1 ar condicionado
sim
1 ar condicionado
sim
sim
1 aspirador
1 sofá
sim
avançar
1
"Rua Lígia, 21"
"sim,"
avançar

**Comment by cynthiabimbi** [comment]
Correçã validada



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/138609130/b9c680e1-f285-4ee2-8d31-cdad635ff60e)
