### ISSUE TITLE
Dúvida no pedido

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#263]
Dentre os itens que requisitei a retirada, estavam 5 caixas de cerveja. No momento do chamado, o sistema leu corretamente, mas notei que foi computado como "garrafas de cerveja/vidro - 5". Fiquei na dúvida se estava correto e resolvi reportar.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/15371e5d-5350-48f1-901c-31db6cab863a)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/768a354c-0faf-410e-9493-bbf0fc52643b)

**Comment by BrunodePauloAlmeida** [comment]
Está correto. Os itens são incluídos na descrição no seguinte formato:

`MATERIAIS A REMOVER: <TIPO DE MATERIAL 1> - <QUANTIDADE DE MATERIAL 1>, <TIPO DE MATERIAL 2> - <QUANTIDADE DE MATERIAL 2>, etc...`

Geralmente a unidade de medida dos materiais são "unidades". Esse item aí coincidiu da unidade de medida ser _caixas/engradados_ e o nome ser _garrafas de cerveja / vidro_. 

@cynthiabimbi posso fazer com que o formato seja 

`MATERIAIS A REMOVER:<UNIDADE DE MEDIDA 1> de <TIPO DE MATERIAL 1> - <QUANTIDADE DE MATERIAL 1>, <UNIDADE DE MEDIDA 2> de <TIPO DE MATERIAL 2> - <QUANTIDADE DE MATERIAL 2>, etc...`

Acha que vale a pena? A descrição pode aumentar razoavelmente de tamanho

**Comment by cynthiabimbi** [comment]
Vamos seguir como está, não mexer.
