### ISSUE TITLE
Complemento pela metade

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#264]
Coloquei um complemente de endereço, mas no momento de ser computado, essa observação ficou incompleta.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/32474d2a-d75f-4752-b414-06fa6dcfc0db)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/80ae7b95-b686-495a-b028-52c649c9e85a)

**Comment by BrunodePauloAlmeida** [comment]
O problema provavelmente foi só na geração do PDF, igual o caso do #216 . Vale checar direto no SGRC, para confirmar.

**Comment by cynthiabimbi** [comment]
ok
