### ISSUE TITLE
Termos não reconhecidos

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#265]
Verifiquei se o sistema faz alguma indicação quando colocamos a palavra "vaso", para ver se faria a diferenciação entre vaso sanitário e vaso de planta, mas isso não ocorreu. Portanto, indico essa alteração, assim como já fizemos com as palavras "cama", "colchão" e "armário". Além disso, não reconheceu o termo "caixa acoplada", que é tão utilizada quanto caixa de descarga.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/ad96fe7b-d452-4b0f-a36a-7806f9dd143a)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/29232e17-edd0-4991-9d47-ec35df168b5a)

**Comment by BrunodePauloAlmeida** [comment]
Certo, mudanças realizadas. Sobem no fim do dia 05/12.


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/e82b2f88-fe28-4791-b591-b23651a4e4d0)

**Comment by BrunodePauloAlmeida** [comment]
![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/9ec37552-57ef-47d0-9087-6c40591a633b)
