### ISSUE TITLE
registro incompleto de complemento

### ISSUE THREAD

**Issue by RobertaColosimo** [prefeitura-rio/chatbot-webhooks#270]
o complemento aparece incompleto do registro do chamado

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152509591/e5f97cfc-9909-4df7-956d-d9e221140e3f)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152509591/eb6c6516-5a83-4c0d-980a-f59db24219da)

**Comment by BrunodePauloAlmeida** [comment]
O problema provavelmente foi só na geração do PDF, igual o caso do #216 . Vale checar direto no SGRC, para confirmar.

**Comment by cynthiabimbi** [comment]
ok
