### ISSUE TITLE
registro incompleto de complemento

### ISSUE THREAD

**Issue by RobertaColosimo** [prefeitura-rio/chatbot-webhooks#271]
Chamado gerado com registro incompleto do complemento

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152509591/6cbcb36e-b6eb-47d9-83ce-31eca610b4a1)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152509591/8899dda2-6a3a-4bc2-b01e-64773e75bdbf)

**Comment by cynthiabimbi** [comment]
ok
