### ISSUE TITLE
Complemento do endereço incompleto

### ISSUE THREAD

**Issue by liviavairo** [prefeitura-rio/chatbot-webhooks#274]
O endereço aparece de forma correta: R. São Francisco Xavier, 89. Contudo, o complemento, "bloco B, apartamento 402", tem o último número cortado.

Chamado:  RIO-27644405-6

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/bfe8e7e1-9d22-49f8-b614-b7d357a58a84)

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/152201205/3f1d6738-c0d1-4412-a95b-c54230638cf1)

**Comment by BrunodePauloAlmeida** [comment]
O problema provavelmente foi só na geração do PDF, igual o caso do #216 . Vale checar direto no SGRC, para confirmar.

**Comment by cynthiabimbi** [comment]
ok
