### ISSUE TITLE
DA - Corrigir texto da opção "4 - Informações gerais"

### ISSUE THREAD

**Issue by tripicchio** [prefeitura-rio/chatbot-webhooks#282]
De 

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/e3696651-84eb-4838-8294-c8a562f951b4)

Para

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/6ee6a59d-1900-4f99-a7f9-76e7213f4fa4)

**Comment by AndreMalheiroPCRJ** [comment]
Correção feita no documento fonte das mensagens, com adequação ao padrão de comunicação estabelecido para o canal chatbot.
