### ISSUE TITLE
DA - Corrigir texto da opção "4 - Informações gerais -> 2 - Informações sobre Desconto"

### ISSUE THREAD

**Issue by tripicchio** [prefeitura-rio/chatbot-webhooks#283]
De

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/2c039667-86f0-4b2c-acd7-8629bde5e431)

Para

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/6722fe54-d9f2-45da-bebd-c53ca44362ad)

**Comment by AndreMalheiroPCRJ** [comment]
Correção feita no documento fonte das mensagens.

**Comment by BrunodePauloAlmeida** [comment]
Corrigido.
