### ISSUE TITLE
DA - Incluir texto explicativo na opção "5 - Cadastrar para receber informações úteis"

### ISSUE THREAD

**Issue by tripicchio** [prefeitura-rio/chatbot-webhooks#284]
De

"Texto explicativo - a ser fornecido pela PGM"

Para

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/bdef3465-c857-408c-a5e4-35bd576257c3)

**Comment by AndreMalheiroPCRJ** [comment]
Inclusão feita no documento fonte das mensagens, com adequação ao padrão de comunicação estabelecido para o canal chatbot.
