### ISSUE TITLE
DA - Erro ao Informar Voltar como Código da Inscrição Imobiliária em "Consultar débitos, parcelamentos e emissão de boletos"

### ISSUE THREAD

**Issue by tripicchio** [prefeitura-rio/chatbot-webhooks#285]
![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/767eedff-24c2-4e38-9f85-7a1200a60636)

**Comment by BrunodePauloAlmeida** [comment]
Erro corrigido. Vi que esse problema estava acontecendo no fluxo 3 também, então aproveitei para corrigir todos.



![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/de63f9cb-d0e7-43cd-b3fc-c82b78537daa)
