### ISSUE TITLE
DA - Exibe mensagem de erro ao consultar por CNPJ específico em "Consultar débitos, parcelamentos e emissão de boletos"

### ISSUE THREAD

**Issue by tripicchio** [prefeitura-rio/chatbot-webhooks#286]
Ao consultar pelo CNPJ 42498634000166, retorna a mensagem **$session.params.api_descricao_erro** em vez exibir a mensagem retornada no response **Sua consulta retornou mais de 20 registros.**

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/155b8fa5-2d98-4bdf-9590-e81fb5e24376)

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/84a04b77-734a-4cc7-8343-2dbe61e09f3f)

**Comment by BrunodePauloAlmeida** [comment]
O problema é o mesmo do issue #287

**Comment by BrunodePauloAlmeida** [comment]
Essa chamada à API demora em média 60 segundos também: A mensagem que seria enviada para o usuário seria essa:

> Sua consulta retornou mais de 20 registros. Blá blá blá (ver qual o limite exato e para onde encaminhar o contribuinte.

![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/10a557c6-bba6-412d-86ae-71f40f13908c)
