### ISSUE TITLE
DA - Erro ao tentar Pagar à vista todas as dívidas não parceladas do CNPJ 34094342000130 em "Consultar débitos, parcelamentos e emissão de boletos"

### ISSUE THREAD

**Issue by tripicchio** [prefeitura-rio/chatbot-webhooks#287]
Pagar à vista do CNPJ 34094342000130 em _Consultar débitos, parcelamentos e emissão de boletos_. Ao informar todas, é exibida a mensagem "Retornando ao menu da Dívida Ativa" em vez de exibir todas as guias de pagamento retornadas para as CDAs/EFs.

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/7cf6c980-60aa-4737-9038-b531a0a0475b)

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/153286267/37232cf0-a8d9-42ed-9031-d0c227a3b10a)

**Comment by BrunodePauloAlmeida** [comment]
O problema aqui é que como são muitos arquivos (11), o endpoint `v2/guiapagamento/emitir/avista` demora muito para responder, o que ativa o time-out do Dialogflow (plataforma que usamos para construir o chatbot), encerrando a conversa abruptamente. 

Tendo em vista que o timeout máximo do DialogFlow é de 30 segundos e que a api está demorando, em média, 60 segundos para responder, eu acho que existem duas soluções:

1. **Solução permanente, mas demorada:** melhorar o tempo de resposta da API da PGM, para que consiga retornar o response em menos de 30 segundos
2. **Solução temporária, mas rápida:** enviar uma mensagem de erro personalizada ao cidadão, nesses casos. Segue exemplo de como funcionaria:


![Image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/544b6698-84bc-4606-adf2-0db602a97681)

**Comment by tripicchio** [comment]
Como o ambiente de homologação em que se encontra a API é lentíssimo, certamente essa situação não ocorrerá com frequência em ambiente de produção.
   Portanto, sugiro adotar a solução 1, porém com mensagem mais amigável ao usuário do que informar "timeout".
