### ISSUE TITLE
REBI - nome do material não é reconhecido quando escrito de forma diferente da lista 

### ISSUE THREAD

**Issue by juliapcrj** [prefeitura-rio/chatbot-webhooks#335]
Na lista de materiais, temos exemplos de telha como:
TELHA DE ALUMINIO
TELHA DE AMIANTO
TELHA FRANCESA/TIJOLO

Mas quando o usuário escreve "Telhas" (de uma forma que não está identico o da lista) o sistema não reconhece.

Isso também acontece no exemplo de armário.

Segue os prints dos casos:

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/160539947/a919ef13-be80-430c-bdf0-5c3dc0b00ea6)
![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/160539947/1d43760f-ba1f-44e6-a678-1390dba7cecd)

Ou seja, solução seria reconhece variações dos materiais. Exemplo: reconhecer "Telha" ou "Telhas" e identificar as opções da lista.

**Comment by BrunodePauloAlmeida** [comment]
Tinha um erro no código de verificação se o item informado pelo usuario estava dentro da lista de itens com sinônimos. Foi corrigido. 25/04 às 16h10
