### ISSUE TITLE
REBI - Bug no fluxo. Aparece informação de outro serviço no meio do fluxo

### ISSUE THREAD

**Issue by juliapcrj** [prefeitura-rio/chatbot-webhooks#343]
Durante o fluxo de REBI, aparece informação do fluxo de IPTU.
Segue o exemplo no print:
![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/160539947/9a3f6369-6126-4dbf-b799-5dfba5943ae1)

**Comment by BrunodePauloAlmeida** [comment]
@gabriel-milan a ASCSAC ainda encerra o atendimento após 30 minutos sem resposta? O Dialogflow encerrou aqui entre as mensagens 7 e 8, então quando o usuário digitou "10", ele estava no começo e foi direcionado pra outro fluxo.

**Comment by gabriel-milan** [comment]
> a ASCSAC ainda encerra o atendimento após 30 minutos sem resposta?

termina em 15 minutos

**Comment by BrunodePauloAlmeida** [comment]
Parece que os 15 minutos da ASCSAC não são sempre 15 minutos... Busquei no meu histórico de conversa no 1746 e peguei alguns casos em que a ASCSAC demorou menos e mais que 15 minutos pra dar timeout.

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/19df8f1a-2799-48c8-b49b-6cc7b693abac)

![image](https://github.com/prefeitura-rio/chatbot-webhooks/assets/42002476/e6c1bcb5-382e-4dc4-af75-c19fce0f9e09)

Não sei se isso é algo que a gente possa (ou deva) tentar resolver. Opiniões? @gabriel-milan

**Comment by gabriel-milan** [comment]
fui averiguar aqui e cada plataforma está com uma configuração de timeout diferente.

- Telegram: 15 minutos
- Messenger: 10 minutos
- WhatsApp: 6 horas

apesar disso, essa inconsistência nos tempos pra expirar chama atenção. eu poderia tentar alterar, pq realmente se a sessão do Dialogflow expirar antes da ASC-SAC, coisas como essa podem acontecer

**Comment by gabriel-milan** [comment]
Vou só confirmar se podemos realizar essa alteração

**Comment by gabriel-milan** [comment]
tivemos aprovação. a modificação já foi realizada para o WhatsApp dar timeout em 15min. testei aqui e funcionou.
